### ISSUE TITLE
Does not download 

### ISSUE THREAD

**Issue by maxs99674** [G3VV/Yank#3]
Shows a 504
![Screenshot_20241021_202959_Brave](https://github.com/user-attachments/assets/ca36e9a4-ad06-4ff7-b50e-2db703ab740e)

**Comment by G3VV** [comment]
I've been having issues with Deezer ratelimiting IPs, I'm trying to implement systems to resolve this. It should be working again though.

**Comment by LINKlang** [comment]
when i try to download my playlist, it still show 504
