### ISSUE TITLE
Playlist not found

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [G3VV/Yank#5]
Hi,

I am trying to download https://open.spotify.com/playlist/6qTJnx81Jwwem0b221CcTv

It does not work. I am having
![image](https://github.com/user-attachments/assets/afe05cab-3244-4542-8bbb-ae3f96a1b4ba)

Is this normal ? Thanks in advance for your help

**Comment by G3VV** [comment]
https://github.com/G3VV/Yank/issues/6
