### ISSUE TITLE
Podcast episodes ?

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [G3VV/Yank#6]
Hi,

I could successfully download tracks from Spotify, but what I'm looking to download is mainly podcasts, and these don't work. I tried to put the ID as a normal track, but it doesn't find the song.

Is that doable somehow ?

Thanks in advance for help

**Comment by G3VV** [comment]
I don't think this'd be doable as Spotify Podcasts are usually stored externally and linked together with an RSS feed.
